
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class PetShopGUI extends javax.swing.JFrame {
    
    //declarar as variáveis aqui: raça, sexo e porte(string), idade e nºde parcelas(int), valor total(double)
    String raca, porte, sexo;
    int numDeParcelas, idade, opcaoPgamaneto;
    double valorTotal=0;
    
    ImageIcon cachorrocaramelo = new javax.swing.ImageIcon(getClass().getResource("/cachorrocaramelo.png"));
    ImageIcon doberman = new javax.swing.ImageIcon(getClass().getResource("/doberman.jpg"));
    ImageIcon dalmata = new javax.swing.ImageIcon(getClass().getResource("/dálmata.jpg"));
    ImageIcon pinscher = new javax.swing.ImageIcon(getClass().getResource("/pinsher.jpeg"));
    ImageIcon poodle = new javax.swing.ImageIcon(getClass().getResource("/poodle.png"));
    /**
     * Creates new form PetShopGUI
     */
    public PetShopGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPorte = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbRaca = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtfIdade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jrbPequeno = new javax.swing.JRadioButton();
        jrbMedio = new javax.swing.JRadioButton();
        jrbGrande = new javax.swing.JRadioButton();
        jrbGigante = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfParcelas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfValorFinal = new javax.swing.JTextField();
        jlImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Orçamento para Banho e Tosa");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Raça:");

        jcbRaca.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jcbRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Dálmata", "Doberman", "Pinscher", "Poodle", "Outra" }));
        jcbRaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbRacaMouseClicked(evt);
            }
        });
        jcbRaca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbRacaItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Sexo:");

        jcbSexo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "M", "F" }));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Idade:");

        jtfIdade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtfIdade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Porte:");

        bgPorte.add(jrbPequeno);
        jrbPequeno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jrbPequeno.setText("Pequeno");

        bgPorte.add(jrbMedio);
        jrbMedio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jrbMedio.setText("Médio");

        bgPorte.add(jrbGrande);
        jrbGrande.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jrbGrande.setText("Grande");
        jrbGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGrandeActionPerformed(evt);
            }
        });

        bgPorte.add(jrbGigante);
        jrbGigante.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jrbGigante.setText("Gigante");
        jrbGigante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGiganteActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("CALCULAR VALOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Parcelas: ");

        jtfParcelas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setText("de");

        jtfValorFinal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jtfParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jtfValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jrbPequeno)
                                                .addGap(18, 18, 18)
                                                .addComponent(jrbMedio)
                                                .addGap(18, 18, 18)
                                                .addComponent(jrbGrande)
                                                .addGap(18, 18, 18)
                                                .addComponent(jrbGigante))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jcbRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(74, 74, 74)
                                                .addComponent(jLabel4)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(78, 78, 78)
                                .addComponent(jlImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jtfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbPequeno)
                            .addComponent(jrbMedio)
                            .addComponent(jrbGrande)
                            .addComponent(jrbGigante))
                        .addGap(56, 56, 56)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtfValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGrandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbGrandeActionPerformed

    private void jrbGiganteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGiganteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbGiganteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        valorTotal=0;
        raca = jcbRaca.getSelectedItem().toString();
        sexo = jcbSexo.getSelectedItem().toString();
        if(jrbPequeno.isSelected()){
            porte = "Pequeno";
        }
        if(jrbMedio.isSelected()){
            porte = "Médio";
        }
        if(jrbGrande.isSelected()){
            porte = "Grande";
        }
        if(jrbGigante.isSelected()){
            porte = "Gigante";
        }
        idade = Integer.parseInt(jtfIdade.getText());
        switch (raca){
            case "Dálmata":
                valorTotal = valorTotal + 100;
                jlImagem.setIcon(dalmata);
                break;
            case "Doberman":
                valorTotal = valorTotal + 80;
                jlImagem.setIcon(doberman);
                break;   
            case "Pinscher":
                valorTotal = valorTotal + 60;
                jlImagem.setIcon(pinscher);
                break;   
            case "Poodle":
                valorTotal = valorTotal + 85;
                jlImagem.setIcon(poodle);
                break;   
            case "Outra":
                valorTotal = valorTotal + 90;
                jlImagem.setIcon(cachorrocaramelo);
                break;                  
        }
        
        switch (sexo){
            case "M":
                valorTotal = valorTotal + 50;
                break;
            case "F":
                valorTotal = valorTotal + 40;
                break;                   
        }
        
        switch (idade){
            case 1:
                valorTotal = valorTotal + 10;
                break;
            case 2:
                valorTotal = valorTotal + 12;
                break;   
            case 3:
                valorTotal = valorTotal + 14;
                break;   
            case 4:
                valorTotal = valorTotal + 16;
                break;   
            case 5:
                valorTotal = valorTotal + 20;
                break;
            case 6:
                valorTotal = valorTotal + 25;
                break;     
            default:
               valorTotal = valorTotal + 35; 
               break;
        }
        
        
        switch (porte){
            case "Pequeno":
                valorTotal = valorTotal + 50;
                break;
            case "Médio":
                valorTotal = valorTotal + 80;
                break;   
            case "Grande":
                valorTotal = valorTotal + 110;
                break;   
            case "Gigante":
                valorTotal = valorTotal + 150;
                break;          
        }
        String []opcoes= {"Cheque","Cartão","Dinheiro"};
        int op = JOptionPane.showOptionDialog(null, "Escolha a Opção", "Opções", 1, 3, null, opcoes, null);
        switch(op){
            case 0:
                
                break;
            case 1:
                valorTotal=valorTotal*1.02;
                break;
            case 2:
                valorTotal=valorTotal/1.05;
                break;    
        }
        if (valorTotal>=200){
            String []opcoesParcelas= {"Uma","Duas","Três"};
        int opParcelas = JOptionPane.showOptionDialog(null, "Escolha a Opção", "Opções", 1, 3, null, opcoesParcelas, null);
        switch(opParcelas){
            case 0:
                jtfParcelas.setText("1");
                jtfValorFinal.setText(""+valorTotal);
                break;
            case 1:
                jtfParcelas.setText("2");
                jtfValorFinal.setText(""+(valorTotal/2));
                break;
            case 2:
                jtfParcelas.setText("3");
                jtfValorFinal.setText(""+(valorTotal/3));
                break;    
        }
        }else{
            jtfParcelas.setText("1");
            jtfValorFinal.setText(""+valorTotal);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbRacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbRacaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbRacaMouseClicked

    private void jcbRacaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbRacaItemStateChanged
        // TODO add your handling code here:
        raca = jcbRaca.getSelectedItem().toString();
        switch (raca){
            case "Dálmata":
                jlImagem.setIcon(dalmata);
                
                break;
            case "Doberman":
                jlImagem.setIcon(doberman);
                break;   
            case "Pinscher":
                jlImagem.setIcon(pinscher);
                break;   
            case "Poodle":
                jlImagem.setIcon(poodle);
                break;   
            case "Outra":
                jlImagem.setIcon(cachorrocaramelo);
                break;                  
        }
    }//GEN-LAST:event_jcbRacaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetShopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetShopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetShopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetShopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetShopGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPorte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jcbRaca;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JLabel jlImagem;
    private javax.swing.JRadioButton jrbGigante;
    private javax.swing.JRadioButton jrbGrande;
    private javax.swing.JRadioButton jrbMedio;
    private javax.swing.JRadioButton jrbPequeno;
    private javax.swing.JTextField jtfIdade;
    private javax.swing.JTextField jtfParcelas;
    private javax.swing.JTextField jtfValorFinal;
    // End of variables declaration//GEN-END:variables
}
